---
version: "3"
services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - /home/ubnt/unifi-data:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PGID
      - PUID
      - TZ
    command: --schedule "0 0 6 * * *" --label-enable --cleanup
    restart: unless-stopped
  traefik:
    image: traefik:v1.7
    command: --web --docker --docker.watch --docker.domain=${DOMAIN} \
             --docker.exposedbydefault=false --acme.domains=${DOMAIN} --loglevel=INFO
    container_name: traefik
    hostname: traefik
    environment:
      - RFC2136_NAMESERVER
      - RFC2136_TSIG_ALGORITHM
      - RFC2136_TSIG_KEY
      - RFC2136_TSIG_SECRET
      - RFC2136_TTL
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/ubnt/traefik-data/acme.json:/acme.json
      - /home/ubnt/traefik-data/traefik.toml:/etc/traefik/traefik.toml
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:ubnt.home.jeffm.io"
      traefik.port: "8080"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped


